### ISSUE TITLE
vJoy Issue

### ISSUE THREAD

**Issue by Max585t** [lshachar/WiiBalanceWalker#8]
The current release of WiiBalanceWalker includes vJoy DLLs that are a version behind the current vJoy release. Also the vJoy links in the readme lead to a dead site.

**Comment by lshachar** [comment]
Do you mean that you get this message:
'Version of Driver (219) does NOT match DLL Version (218)' ?
This should not break anything. (let me know if you mean something else!)

The vjoy links in the readme currently leads to a website that reads:
"This site is down as it has been infected by viruses
Download is available from:
https://sourceforge.net/projects/vjoystick/
You can also look for valid versions of vJoy on GitHab."

-So, I guess this might've changed since 8 days ago when you posted. I hope Shaul will sort out his website's issues (but at least there's a valid link to download vjoy)

Thanks for posting!
